# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: uSocial
email: dan_wang@alumni.brown.edu
description: > # this means to ignore newlines until "baseurl:"
  A social network that breaks the rules &ndash; by putting users first.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.usocial.xyz" # the base hostname & protocol for your site
twitter_username: teabylila
github_username: danwang1995

# Build settings
markdown: kramdown
